# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#

# Seed Instrument Skills

Skill.create(name: "Bass")
Skill.create(name: "Drums")
Skill.create(name: "Keyboards")
Skill.create(name: "Vocals")
Skill.create(name: "Background Vocals")
Skill.create(name: "Piano")
Skill.create(name: "Organ")
Skill.create(name: "Synths")
Skill.create(name: "Beatmaking")
Skill.create(name: "Electric Guitar")
Skill.create(name: "Classical Guitar")
Skill.create(name: "Acoustic Guitar")
Skill.create(name: "Lapsteel Guitar")
Skill.create(name: "Tenor Saxophone")
Skill.create(name: "Alto Saxophone")
Skill.create(name: "Soprano Saxophone")
Skill.create(name: "Baritone Saxophone")
Skill.create(name: "Clarinet")
Skill.create(name: "Bass Clarinet")
Skill.create(name: "Flute")
Skill.create(name: "Double Bass")
Skill.create(name: "Violin")
Skill.create(name: "Cello")
Skill.create(name: "Viola")
Skill.create(name: "Trumpet")
Skill.create(name: "Trombone")
Skill.create(name: "Tuba")
Skill.create(name: "Horn")
Skill.create(name: "Harp")
Skill.create(name: "Percussion")
Skill.create(name: "Classical Percussion")
Skill.create(name: "Oboe")
Skill.create(name: "Bassoon")
Skill.create(name: "Traditional Instruments")
Skill.create(name: "DJ")
Skill.create(name: "MC")

# Seed Musical Skills
Skill.create(name: "Arranger")
Skill.create(name: "Producer")
Skill.create(name: "Composer")
Skill.create(name: "Lyricist")
Skill.create(name: "Songwriter")
Skill.create(name: "Sound Designer")
Skill.create(name: "Conductor")
Skill.create(name: "Synth Programming")
Skill.create(name: "Copyist")
Skill.create(name: "Music Director")

# Seed Technical Skills
Skill.create(name: "Recording Engineer")
Skill.create(name: "FOH Engineer")
Skill.create(name: "Mixing Engineer")
Skill.create(name: "Mastering Engineer")
Skill.create(name: "Monitor Engineer")
Skill.create(name: "Lighting Technician")
Skill.create(name: "Maintenance Engineer")
Skill.create(name: "Pro Tools Operator")
Skill.create(name: "Ableton Programmer")
Skill.create(name: "Luthier")

# Seed Business Skills
Skill.create(name: "A&R Manager")
Skill.create(name: "A&R Director")
Skill.create(name: "Label Mananger")
Skill.create(name: "Label Director")
Skill.create(name: "Artist Manager")
Skill.create(name: "Marketing Manager")
Skill.create(name: "Media Relations / PR")
Skill.create(name: "Executive")
Skill.create(name: "Business Affair")
Skill.create(name: "Distribution Manager")
Skill.create(name: "Merchandiser")
Skill.create(name: "Music Attorney")
Skill.create(name: "Music Supervisor")
Skill.create(name: "New Media Manager")
Skill.create(name: "Office Manager")
Skill.create(name: "Project Manager")
Skill.create(name: "Promotions Department")
Skill.create(name: "Radio Producer")
Skill.create(name: "Radio Programmer")
Skill.create(name: "Radio Promotion")
Skill.create(name: "Radio Talent")
Skill.create(name: "Royalty Accounts")
Skill.create(name: "Sales")

# Live
Skill.create(name: "Festival Organizer")
Skill.create(name: "Booking Agent")
Skill.create(name: "Promoter")
Skill.create(name: "Technical Director")
Skill.create(name: "Technician, Backliner")
Skill.create(name: "Road Manager")
Skill.create(name: "Tour Manager")
Skill.create(name: "Tour Producer")
Skill.create(name: "Venue Director")

# Other Skills
Skill.create(name: "Music Journalist")
Skill.create(name: "Music Teacher")
Skill.create(name: "Music Therapist")
Skill.create(name: "Musicologist")


